#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Statelab3ClassLibrary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StatesDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertState(State instance);
    partial void UpdateState(State instance);
    partial void DeleteState(State instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Statelab3ClassLibrary.Properties.Settings.Default.StatesDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<State> States
		{
			get
			{
				return this.GetTable<State>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.States")]
	public partial class State : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _STATE_NAME;
		
		private System.Nullable<int> _STATE_POPULATION;
		
		private string _FLAG_DESCRIPTION;
		
		private string _STATE_FLOWER;
		
		private string _STATE_BIRD;
		
		private string _STATE_COLOR;
		
		private string _LARGEST_CITIES;
		
		private string _STATE_CAPITAL;
		
		private System.Nullable<decimal> _MEDIAN_INCOME;
		
		private System.Nullable<double> _COMPUTER_JOB_PERCENTAGE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSTATE_NAMEChanging(string value);
    partial void OnSTATE_NAMEChanged();
    partial void OnSTATE_POPULATIONChanging(System.Nullable<int> value);
    partial void OnSTATE_POPULATIONChanged();
    partial void OnFLAG_DESCRIPTIONChanging(string value);
    partial void OnFLAG_DESCRIPTIONChanged();
    partial void OnSTATE_FLOWERChanging(string value);
    partial void OnSTATE_FLOWERChanged();
    partial void OnSTATE_BIRDChanging(string value);
    partial void OnSTATE_BIRDChanged();
    partial void OnSTATE_COLORChanging(string value);
    partial void OnSTATE_COLORChanged();
    partial void OnLARGEST_CITIESChanging(string value);
    partial void OnLARGEST_CITIESChanged();
    partial void OnSTATE_CAPITALChanging(string value);
    partial void OnSTATE_CAPITALChanged();
    partial void OnMEDIAN_INCOMEChanging(System.Nullable<decimal> value);
    partial void OnMEDIAN_INCOMEChanged();
    partial void OnCOMPUTER_JOB_PERCENTAGEChanging(System.Nullable<double> value);
    partial void OnCOMPUTER_JOB_PERCENTAGEChanged();
    #endregion
		
		public State()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_NAME", DbType="NVarChar(100)")]
		public string STATE_NAME
		{
			get
			{
				return this._STATE_NAME;
			}
			set
			{
				if ((this._STATE_NAME != value))
				{
					this.OnSTATE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._STATE_NAME = value;
					this.SendPropertyChanged("STATE_NAME");
					this.OnSTATE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_POPULATION", DbType="Int")]
		public System.Nullable<int> STATE_POPULATION
		{
			get
			{
				return this._STATE_POPULATION;
			}
			set
			{
				if ((this._STATE_POPULATION != value))
				{
					this.OnSTATE_POPULATIONChanging(value);
					this.SendPropertyChanging();
					this._STATE_POPULATION = value;
					this.SendPropertyChanged("STATE_POPULATION");
					this.OnSTATE_POPULATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG_DESCRIPTION", DbType="NVarChar(MAX)")]
		public string FLAG_DESCRIPTION
		{
			get
			{
				return this._FLAG_DESCRIPTION;
			}
			set
			{
				if ((this._FLAG_DESCRIPTION != value))
				{
					this.OnFLAG_DESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._FLAG_DESCRIPTION = value;
					this.SendPropertyChanged("FLAG_DESCRIPTION");
					this.OnFLAG_DESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_FLOWER", DbType="NVarChar(100)")]
		public string STATE_FLOWER
		{
			get
			{
				return this._STATE_FLOWER;
			}
			set
			{
				if ((this._STATE_FLOWER != value))
				{
					this.OnSTATE_FLOWERChanging(value);
					this.SendPropertyChanging();
					this._STATE_FLOWER = value;
					this.SendPropertyChanged("STATE_FLOWER");
					this.OnSTATE_FLOWERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_BIRD", DbType="NVarChar(100)")]
		public string STATE_BIRD
		{
			get
			{
				return this._STATE_BIRD;
			}
			set
			{
				if ((this._STATE_BIRD != value))
				{
					this.OnSTATE_BIRDChanging(value);
					this.SendPropertyChanging();
					this._STATE_BIRD = value;
					this.SendPropertyChanged("STATE_BIRD");
					this.OnSTATE_BIRDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_COLOR", DbType="NVarChar(255)")]
		public string STATE_COLOR
		{
			get
			{
				return this._STATE_COLOR;
			}
			set
			{
				if ((this._STATE_COLOR != value))
				{
					this.OnSTATE_COLORChanging(value);
					this.SendPropertyChanging();
					this._STATE_COLOR = value;
					this.SendPropertyChanged("STATE_COLOR");
					this.OnSTATE_COLORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LARGEST_CITIES", DbType="NVarChar(MAX)")]
		public string LARGEST_CITIES
		{
			get
			{
				return this._LARGEST_CITIES;
			}
			set
			{
				if ((this._LARGEST_CITIES != value))
				{
					this.OnLARGEST_CITIESChanging(value);
					this.SendPropertyChanging();
					this._LARGEST_CITIES = value;
					this.SendPropertyChanged("LARGEST_CITIES");
					this.OnLARGEST_CITIESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_CAPITAL", DbType="NVarChar(100)")]
		public string STATE_CAPITAL
		{
			get
			{
				return this._STATE_CAPITAL;
			}
			set
			{
				if ((this._STATE_CAPITAL != value))
				{
					this.OnSTATE_CAPITALChanging(value);
					this.SendPropertyChanging();
					this._STATE_CAPITAL = value;
					this.SendPropertyChanged("STATE_CAPITAL");
					this.OnSTATE_CAPITALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEDIAN_INCOME", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> MEDIAN_INCOME
		{
			get
			{
				return this._MEDIAN_INCOME;
			}
			set
			{
				if ((this._MEDIAN_INCOME != value))
				{
					this.OnMEDIAN_INCOMEChanging(value);
					this.SendPropertyChanging();
					this._MEDIAN_INCOME = value;
					this.SendPropertyChanged("MEDIAN_INCOME");
					this.OnMEDIAN_INCOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPUTER_JOB_PERCENTAGE", DbType="Float")]
		public System.Nullable<double> COMPUTER_JOB_PERCENTAGE
		{
			get
			{
				return this._COMPUTER_JOB_PERCENTAGE;
			}
			set
			{
				if ((this._COMPUTER_JOB_PERCENTAGE != value))
				{
					this.OnCOMPUTER_JOB_PERCENTAGEChanging(value);
					this.SendPropertyChanging();
					this._COMPUTER_JOB_PERCENTAGE = value;
					this.SendPropertyChanged("COMPUTER_JOB_PERCENTAGE");
					this.OnCOMPUTER_JOB_PERCENTAGEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
